apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::525256174617:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16ZOY35P1SU4J
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-21T01:02:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1723"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7fbe4168-f382-4c37-969d-05008720bb58
